--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2
-- Dumped by pg_dump version 11.2

-- Started on 2019-07-17 23:13:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 196 (class 1259 OID 49272)
-- Name: equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment (
    equipment_id integer NOT NULL,
    equipment_name character varying,
    equipment_type character varying,
    armor integer,
    damage integer,
    durability integer,
    amount integer,
    hero_id integer
);


ALTER TABLE public.equipment OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 65624)
-- Name: armor_equipment; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.armor_equipment AS
 SELECT eq.equipment_id,
    eq.equipment_name,
    eq.equipment_type,
    eq.armor,
    eq.damage,
    eq.durability,
    eq.amount,
    eq.hero_id
   FROM public.equipment eq
  WHERE (eq.armor IS NOT NULL);


ALTER TABLE public.armor_equipment OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 57450)
-- Name: big_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.big_data (
    id integer NOT NULL,
    big_number integer,
    some_text character varying(100),
    random_price numeric(10,2)
);


ALTER TABLE public.big_data OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 57448)
-- Name: big_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.big_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.big_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 65628)
-- Name: big_view; Type: MATERIALIZED VIEW; Schema: public; Owner: postgres
--

CREATE MATERIALIZED VIEW public.big_view AS
 SELECT count(big_data.big_number) AS count,
    array_agg(big_data.some_text) AS array_agg,
    (avg(big_data.random_price))::numeric(10,2) AS avg
   FROM public.big_data
  GROUP BY big_data.big_number
 HAVING ((avg(big_data.random_price) > (300)::numeric) AND (count(big_data.big_number) > 2))
  WITH NO DATA;


ALTER TABLE public.big_view OWNER TO postgres;

--
-- TOC entry 197 (class 1259 OID 49278)
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment ALTER COLUMN equipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 57455)
-- Name: generate_data; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.generate_data AS
 SELECT (((hundred.hundreds * 100) + (ten.tens * 10)) + one.ones) AS numbers
   FROM ((( SELECT unnest(ARRAY[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) AS tens) ten
     CROSS JOIN ( SELECT unnest(ARRAY[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) AS ones) one)
     CROSS JOIN ( SELECT unnest(ARRAY[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) AS hundreds) hundred)
  ORDER BY (((hundred.hundreds * 100) + (ten.tens * 10)) + one.ones);


ALTER TABLE public.generate_data OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 57459)
-- Name: generate_chars; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.generate_chars AS
 SELECT chr(gd1.numbers) AS chr
   FROM (public.generate_data gd1
     CROSS JOIN public.generate_data gd2)
  WHERE ((gd1.numbers >= 33) AND (gd1.numbers <= 126));


ALTER TABLE public.generate_chars OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 49280)
-- Name: heroes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.heroes (
    first_name character varying,
    last_name character varying,
    gender character(1),
    race character varying,
    strength integer,
    wisdom integer,
    health integer DEFAULT 200,
    mana integer,
    hero_id integer NOT NULL,
    birthdate date,
    is_teamleader boolean DEFAULT false NOT NULL,
    gold numeric(10,2) DEFAULT 0 NOT NULL
);


ALTER TABLE public.heroes OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 57424)
-- Name: heroes_equipment_count; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.heroes_equipment_count AS
 SELECT h.first_name,
    h.last_name,
    h.race,
    count(e.equipment_id) AS count
   FROM (public.heroes h
     JOIN public.equipment e ON ((h.hero_id = e.hero_id)))
  WHERE ((h.race)::text = ANY ((ARRAY['elf'::character varying, 'krasnolud'::character varying])::text[]))
  GROUP BY h.first_name, h.last_name, h.race
 HAVING (count(e.equipment_id) > 1);


ALTER TABLE public.heroes_equipment_count OWNER TO postgres;

--
-- TOC entry 199 (class 1259 OID 49288)
-- Name: heroes_hero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.heroes ALTER COLUMN hero_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.heroes_hero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 57463)
-- Name: random_strings; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.random_strings AS
 SELECT string_agg(generate_chars.chr, ''::text) AS random_string
   FROM public.generate_chars
  GROUP BY (round((random() * (10000)::double precision)));


ALTER TABLE public.random_strings OWNER TO postgres;

--
-- TOC entry 201 (class 1259 OID 57444)
-- Name: tank_heroes; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.tank_heroes AS
 SELECT heroes.hero_id,
    heroes.first_name,
    heroes.last_name,
    heroes.health
   FROM public.heroes
  WHERE (heroes.health > 200)
  WITH CASCADED CHECK OPTION;


ALTER TABLE public.tank_heroes OWNER TO postgres;

--
-- TOC entry 2870 (class 0 OID 57450)
-- Dependencies: 203
-- Data for Name: big_data; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2865 (class 0 OID 49272)
-- Dependencies: 196
-- Data for Name: equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (46, 'sztylet', 'broń', NULL, 2, NULL, 2, 1);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (47, 'szabla', ' broń', NULL, 4, NULL, 1, 1);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (48, 'pałasz', ' broń', NULL, 6, NULL, 1, 2);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (49, 'miecz dwuręczny', ' broń', NULL, 22, NULL, 1, 3);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (50, 'długi łuk', ' broń', NULL, 5, NULL, 1, 4);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (51, 'topór', ' broń', NULL, 11, NULL, 1, 5);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (52, 'różdżka', ' broń', NULL, NULL, 20, 1, 6);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (53, 'lekka kusza', ' broń', NULL, 8, NULL, 1, 7);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (54, 'kolczuga', ' uzbrojenie', 3, NULL, NULL, 1, 3);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (55, 'lekka zbroja', ' uzbrojenie', 7, NULL, NULL, 1, 6);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (56, 'zbroja płytowa', ' uzbrojenie', 22, NULL, NULL, 1, 4);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (57, 'szyszak', ' uzbrojenie', 2, NULL, NULL, 1, 2);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (58, 'hełm', ' uzbrojenie', 4, NULL, NULL, 1, 3);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (59, 'hełm', ' uzbrojenie', 4, NULL, NULL, 1, 4);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (60, 'puklerz', ' uzbrojenie', 2, NULL, NULL, 1, 5);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (61, 'duża tarcza', ' uzbrojenie', 9, NULL, NULL, 1, 6);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (62, 'kolczuga', ' uzbrojenie', 3, NULL, NULL, 1, 1);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (63, 'lekka zbroja', ' uzbrojenie', 7, NULL, NULL, 1, NULL);
INSERT INTO public.equipment (equipment_id, equipment_name, equipment_type, armor, damage, durability, amount, hero_id) VALUES (64, 'zbroja płytowa', ' uzbrojenie', 22, NULL, NULL, 1, NULL);


--
-- TOC entry 2867 (class 0 OID 49280)
-- Dependencies: 198
-- Data for Name: heroes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Brass', 'Comtel', 'M', 'elf', 15, 19, 150, 210, 1, '1948-02-25', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Jared', 'Brewster', 'M', 'człowiek', 15, 10, 200, 50, 2, '1966-05-20', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Olive', 'Ironfist', 'M', 'krasnolud', 32, 8, 350, 120, 4, '1960-02-05', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Moira', 'Srebrnolica', 'K', 'krasnolud', 38, 12, 370, 130, 8, '1890-08-05', true, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Axel', 'deBoom', 'M', 'krasnolud', 35, 5, 280, 190, 7, '1900-01-03', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Mika', 'Kleefan', 'K', 'człowiek', 20, 25, 230, 250, 5, '1966-05-20', true, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Fandrel', 'Glowhand', 'M', 'elf', 15, 32, 130, 210, 6, '1820-11-10', true, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Gal', 'Krzywonóg', 'K', 'hobbit', 12, 10, 120, 10, 3, '1977-11-03', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Brandon', 'Tuk', 'M', 'hobbit', 22, 12, 160, 0, 9, '1970-12-05', false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Jan', 'Błysk', 'M', 'człowiek', 5, 30, 130, 450, 10, NULL, false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Super', 'Tank', NULL, NULL, NULL, NULL, 410, NULL, 17, NULL, false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Super', 'Tank', NULL, NULL, NULL, NULL, 410, NULL, 18, NULL, false, 0.00);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate, is_teamleader, gold) VALUES ('Mistery', 'Girl', NULL, NULL, NULL, NULL, 110, NULL, 19, NULL, false, 0.00);


--
-- TOC entry 2877 (class 0 OID 0)
-- Dependencies: 202
-- Name: big_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.big_data_id_seq', 500006, true);


--
-- TOC entry 2878 (class 0 OID 0)
-- Dependencies: 197
-- Name: equipment_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipment_id_seq', 65, false);


--
-- TOC entry 2879 (class 0 OID 0)
-- Dependencies: 199
-- Name: heroes_hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.heroes_hero_id_seq', 19, true);


--
-- TOC entry 2736 (class 2606 OID 57454)
-- Name: big_data big_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.big_data
    ADD CONSTRAINT big_data_pkey PRIMARY KEY (id);


--
-- TOC entry 2732 (class 2606 OID 49293)
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id);


--
-- TOC entry 2734 (class 2606 OID 49291)
-- Name: heroes heroes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.heroes
    ADD CONSTRAINT heroes_pkey PRIMARY KEY (hero_id);


--
-- TOC entry 2871 (class 0 OID 65628)
-- Dependencies: 208 2873
-- Name: big_view; Type: MATERIALIZED VIEW DATA; Schema: public; Owner: postgres
--

REFRESH MATERIALIZED VIEW public.big_view;


-- Completed on 2019-07-17 23:13:55

--
-- PostgreSQL database dump complete
--

