-- Przywrócenie oryginalnych wartości w kolumnie 'hero_id'
UPDATE heroes SET hero_id = hero_id - 10;

-- Zmiana kolumny 'hero_id' na autoinkrementującą
ALTER TABLE heroes ALTER COLUMN hero_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Próba dodania nowego rekordu
-- Z powodu nie ustawionej sekwencji, jest konflikt przy próbie przypisania nowego hero_id
INSERT INTO heroes VALUES ('Mika', 'Kleefan', 'M', 'człowiek', 20, 25, 220, 250);

-- Wyświetlenie atrybutów sekwencji (PostgreSQL)
SELECT * FROM pg_sequences;

-- Przestawienie startu wartości generowanych przez sekwencję na 6 (pierwsza wolna w naszym zestawie danych)
ALTER SEQUENCE heroes_hero_id_seq RESTART WITH 6;

-- Udane dodanie nowego rekordu
INSERT INTO heroes VALUES ('Mika', 'Kleefan', 'M', 'człowiek', 20, 25, 220, 250);

-- Wyświetlenie wszystkich rekordów (w tym nowo dodanego z automatycznie wygenerowanym hero_id)
SELECT * FROM heroes;
