--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 10.5

--
-- Name: heroes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.heroes (
    first_name character varying,
    last_name character varying,
    gender character(1),
    race character varying,
    strength integer NOT NULL,
    wisdom integer,
    health integer DEFAULT 200,
    mana integer,
    hero_id integer NOT NULL,
    birthday date,
    CONSTRAINT heroes_gender_check CHECK ((gender = ANY (ARRAY['M'::bpchar, 'K'::bpchar])))
);


ALTER TABLE public.heroes OWNER TO postgres;

--
-- Name: heroes_hero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.heroes ALTER COLUMN hero_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.heroes_hero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: heroes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Jared', 'Brewster', 'M', 'człowiek', 15, 10, 200, 50, 2, '1966-05-20');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Gal', 'Krzywonóg', 'K', 'hobbit', 12, 10, 200, 10, 3, '1977-11-03');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Olive', 'Ironfist', 'M', 'krasnolud', 32, 8, 200, 120, 4, '1960-02-05');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Mika', 'Kleefan', 'K', 'człowiek', 20, 25, 200, 250, 5, '1966-05-20');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Fandrel', 'Glowhand', 'M', 'elf', 15, 32, 200, 210, 6, '1820-11-10');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Axel', 'deBoom', 'M', 'krasnolud', 35, 5, 200, 190, 7, '1900-01-03');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Moira', 'Srebrnolica', 'K', 'krasnolud', 38, 12, 200, 130, 8, '1890-08-05');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Brandon', 'Tuk', 'M', 'hobbit', 22, 12, 200, 0, 9, '1970-12-05');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Robert', 'Shower', 'M', 'człowiek', 20, 25, 220, 250, 10, NULL);
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Johnny', 'Monotonic', 'M', 'człowiek', 23, 33, 250, 390, 11, '1995-11-17');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Axel', 'Pulley', 'M', 'człowiek', 19, 21, 170, 230, 12, '1984-12-01');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Xena', 'Flawless', 'K', 'człowiek', 31, 10, 320, 90, 13, '1995-09-04');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Frandel', 'Goldleaf', 'K', 'elf', 11, 225, 120, 590, 14, '1895-09-04');
INSERT INTO public.heroes (first_name, last_name, gender, race, strength, wisdom, health, mana, hero_id, birthdate) VALUES ('Brass', 'Comtel', 'M', 'elf', 15, 19, 150, 210, 1, '1948-02-25');



--
-- Name: heroes_hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.heroes_hero_id_seq', 14, true);


--
-- Name: heroes heroes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.heroes
    ADD CONSTRAINT heroes_pkey PRIMARY KEY (hero_id);


--
-- PostgreSQL database dump complete
--

