--
-- PostgreSQL database dump
--

-- Dumped from database version 10.5
-- Dumped by pg_dump version 10.5


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment (
    equipment_id integer NOT NULL,
    equipment_name character varying,
    equipment_type character varying,
    armor integer,
    damage integer,
    durability integer,
    amount integer,
    hero_id integer
);


ALTER TABLE public.equipment OWNER TO postgres;

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment ALTER COLUMN equipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: heroes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.heroes (
    first_name character varying,
    last_name character varying,
    gender character(1),
    race character varying,
    strength integer,
    wisdom integer,
    health integer DEFAULT 200,
    mana integer,
    hero_id integer NOT NULL,
    birthdate date,
    is_teamleader boolean NOT NULL DEFAULT False,
    gold decimal(10,2) DEFAULT 0 NOT NULL
);


ALTER TABLE public.heroes OWNER TO postgres;

--
-- Name: heroes_hero_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.heroes ALTER COLUMN hero_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.heroes_hero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Data for Name: equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.equipment VALUES (46, 'sztylet', 'broń', NULL, 2, NULL, 2, 1);
INSERT INTO public.equipment VALUES (47, 'szabla', ' broń', NULL, 4, NULL, 1, 1);
INSERT INTO public.equipment VALUES (48, 'pałasz', ' broń', NULL, 6, NULL, 1, 2);
INSERT INTO public.equipment VALUES (49, 'miecz dwuręczny', ' broń', NULL, 22, NULL, 1, 3);
INSERT INTO public.equipment VALUES (50, 'długi łuk', ' broń', NULL, 5, NULL, 1, 4);
INSERT INTO public.equipment VALUES (51, 'topór', ' broń', NULL, 11, NULL, 1, 5);
INSERT INTO public.equipment VALUES (52, 'różdżka', ' broń', NULL, NULL, 20, 1, 6);
INSERT INTO public.equipment VALUES (53, 'lekka kusza', ' broń', NULL, 8, NULL, 1, 7);
INSERT INTO public.equipment VALUES (54, 'kolczuga', ' uzbrojenie', 3, NULL, NULL, 1, 3);
INSERT INTO public.equipment VALUES (55, 'lekka zbroja', ' uzbrojenie', 7, NULL, NULL, 1, 6);
INSERT INTO public.equipment VALUES (56, 'zbroja płytowa', ' uzbrojenie', 22, NULL, NULL, 1, 4);
INSERT INTO public.equipment VALUES (57, 'szyszak', ' uzbrojenie', 2, NULL, NULL, 1, 2);
INSERT INTO public.equipment VALUES (58, 'hełm', ' uzbrojenie', 4, NULL, NULL, 1, 3);
INSERT INTO public.equipment VALUES (59, 'hełm', ' uzbrojenie', 4, NULL, NULL, 1, 4);
INSERT INTO public.equipment VALUES (60, 'puklerz', ' uzbrojenie', 2, NULL, NULL, 1, 5);
INSERT INTO public.equipment VALUES (61, 'duża tarcza', ' uzbrojenie', 9, NULL, NULL, 1, 6);
INSERT INTO public.equipment VALUES (62, 'kolczuga', ' uzbrojenie', 3, NULL, NULL, 1, 1);
INSERT INTO public.equipment VALUES (63, 'lekka zbroja', ' uzbrojenie', 7, NULL, NULL, 1, NULL);
INSERT INTO public.equipment VALUES (64, 'zbroja płytowa', ' uzbrojenie', 22, NULL, NULL, 1, NULL);


--
-- Data for Name: heroes; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.heroes VALUES ('Brass', 'Comtel', 'M', 'elf', 15, 19, 150, 210, 1, '1948-02-25', false, 0);
INSERT INTO public.heroes VALUES ('Jared', 'Brewster', 'M', 'człowiek', 15, 10, 200, 50, 2, '1966-05-20', false, 0);
INSERT INTO public.heroes VALUES ('Olive', 'Ironfist', 'M', 'krasnolud', 32, 8, 350, 120, 4, '1960-02-05', false, 0);
INSERT INTO public.heroes VALUES ('Moira', 'Srebrnolica', 'K', 'krasnolud', 38, 12, 370, 130, 8, '1890-08-05', true, 0);
INSERT INTO public.heroes VALUES ('Axel', 'deBoom', 'M', 'krasnolud', 35, 5, 280, 190, 7, '1900-01-03', false, 0);
INSERT INTO public.heroes VALUES ('Mika', 'Kleefan', 'K', 'człowiek', 20, 25, 230, 250, 5, '1966-05-20', true, 0);
INSERT INTO public.heroes VALUES ('Fandrel', 'Glowhand', 'M', 'elf', 15, 32, 130, 210, 6, '1820-11-10', true, 0);
INSERT INTO public.heroes VALUES ('Gal', 'Krzywonóg', 'K', 'hobbit', 12, 10, 120, 10, 3, '1977-11-03', false, 0);
INSERT INTO public.heroes VALUES ('Brandon', 'Tuk', 'M', 'hobbit', 22, 12, 160, 0, 9, '1970-12-05', false, 0);
INSERT INTO public.heroes VALUES ('Jan', 'Błysk', 'M', 'człowiek', 5, 30, 130, 450, 10, NULL, false, 0);

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipment_id_seq', 65, false);

--
-- Name: heroes_hero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.heroes_hero_id_seq', 11, true);


--
-- Name: heroes heroes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.heroes
    ADD CONSTRAINT heroes_pkey PRIMARY KEY (hero_id);

--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id);

--
-- PostgreSQL database dump complete
--

